//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazy.Vinke.Json.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LazyResourcesJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LazyResourcesJson() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lazy.Vinke.Json.Properties.LazyResourcesJson", typeof(LazyResourcesJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid array item on line {0}! Accept only &quot;Array | Object | String | Integer | Decimal | null | true | false&quot;, got &quot;{1}&quot;!.
        /// </summary>
        public static string LazyJsonReaderInvalidArrayItem {
            get {
                return ResourceManager.GetString("LazyJsonReaderInvalidArrayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid object property value on line {0}! Accept only &quot;Array | Object | String | Integer | Decimal | null | true | false&quot;, got &quot;{1}&quot;!.
        /// </summary>
        public static string LazyJsonReaderInvalidObjectPropertyValue {
            get {
                return ResourceManager.GetString("LazyJsonReaderInvalidObjectPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Duplicated property on line {0}! Property name: &quot;{1}&quot;!.
        /// </summary>
        public static string LazyJsonReaderObjectPropertyDuplicated {
            get {
                return ResourceManager.GetString("LazyJsonReaderObjectPropertyDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unexpected character read on line {0}! Expected &quot;{1}&quot;, got &quot;{2}&quot;!.
        /// </summary>
        public static string LazyJsonReaderUnexpectedCharacter {
            get {
                return ResourceManager.GetString("LazyJsonReaderUnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unexpected token read on line {0}! Expected &quot;{1}&quot;, got &quot;{2}&quot;!.
        /// </summary>
        public static string LazyJsonReaderUnexpectedToken {
            get {
                return ResourceManager.GetString("LazyJsonReaderUnexpectedToken", resourceCulture);
            }
        }
    }
}
