//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazy.Vinke.Database.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lazy.Vinke.Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database connection is already closed!.
        /// </summary>
        public static string LazyDatabaseExceptionConnectionAlreadyClosed {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionConnectionAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database connection is already open!.
        /// </summary>
        public static string LazyDatabaseExceptionConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database connection is not open!.
        /// </summary>
        public static string LazyDatabaseExceptionConnectionNotOpen {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionConnectionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database connection string cannot be null or empty!.
        /// </summary>
        public static string LazyDatabaseExceptionConnectionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionConnectionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The datarow cannot be null and must have at least on column!.
        /// </summary>
        public static string LazyDatabaseExceptionDataRowNullOrColumnZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionDataRowNullOrColumnZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The datatable cannot be null and must have at least one row!.
        /// </summary>
        public static string LazyDatabaseExceptionDataTableNullOrRowsZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionDataTableNullOrRowsZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The datatable must have at least one primary key column!.
        /// </summary>
        public static string LazyDatabaseExceptionDataTablePrimaryKeyNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionDataTablePrimaryKeyNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The datatable rows must have at least one column!.
        /// </summary>
        public static string LazyDatabaseExceptionDataTableRowsColumnsZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionDataTableRowsColumnsZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The fields array and values array must have the same number of elements!.
        /// </summary>
        public static string LazyDatabaseExceptionFieldsAndValuesNotMatch {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionFieldsAndValuesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The fields array cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionFieldsNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionFieldsNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The increment field cannot be null or empty!.
        /// </summary>
        public static string LazyDatabaseExceptionIncrementFieldNullOrEmpty {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionIncrementFieldNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The increment range cannot be lower than one!.
        /// </summary>
        public static string LazyDatabaseExceptionIncrementRangeLowerThanOne {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionIncrementRangeLowerThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The key fields array and key values array must have the same number of elements!.
        /// </summary>
        public static string LazyDatabaseExceptionKeyFieldsAndKeyValuesNotMatch {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionKeyFieldsAndKeyValuesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The key fields array cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionKeyFieldsNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionKeyFieldsNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The key values array list cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionKeyValuesListNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionKeyValuesListNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The key values array cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionKeyValuesNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionKeyValuesNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The non key fields array and non key values array must have the same number of elements!.
        /// </summary>
        public static string LazyDatabaseExceptionNonKeyFieldsAndNonKeyValuesNotMatch {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionNonKeyFieldsAndNonKeyValuesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The non key fields array cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionNonKeyFieldsNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionNonKeyFieldsNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The non key values array list and key values array list must have the same number of elements!.
        /// </summary>
        public static string LazyDatabaseExceptionNonKeyValuesListAndKeyValueListNotMatch {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionNonKeyValuesListAndKeyValueListNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The non key values array list cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionNonKeyValuesListNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionNonKeyValuesListNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The non key values array cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionNonKeyValuesNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionNonKeyValuesNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The procedure name cannot be null or empty!.
        /// </summary>
        public static string LazyDatabaseExceptionProcedureNameNullOrEmpty {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionProcedureNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The return fields cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionReturnFieldsNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionReturnFieldsNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The sql sentence cannot be null or empty!.
        /// </summary>
        public static string LazyDatabaseExceptionSqlNullOrEmpty {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionSqlNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The table name cannot be null or empty!.
        /// </summary>
        public static string LazyDatabaseExceptionTableNameNullOrEmpty {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionTableNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database transaction was already started!.
        /// </summary>
        public static string LazyDatabaseExceptionTransactionAlreadyStarted {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionTransactionAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The database transaction was not initialized!.
        /// </summary>
        public static string LazyDatabaseExceptionTransactionNotInitialized {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionTransactionNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The values array and parameters array must have the same number of elements!.
        /// </summary>
        public static string LazyDatabaseExceptionValuesAndParametersNotMatch {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionValuesAndParametersNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The values array list and key values array list must have the same number of elements!.
        /// </summary>
        public static string LazyDatabaseExceptionValuesListAndKeyValueListNotMatch {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionValuesListAndKeyValueListNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The values array list cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionValuesListNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionValuesListNullOrZeroLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The values array cannot be null or zero lenght!.
        /// </summary>
        public static string LazyDatabaseExceptionValuesNullOrZeroLenght {
            get {
                return ResourceManager.GetString("LazyDatabaseExceptionValuesNullOrZeroLenght", resourceCulture);
            }
        }
    }
}
